var test = require('tape')
var intervalQuality = require('../../lib/pitch/interval-quality.js')

test('intervalQuality()', function (t) {
  t.equal(intervalQuality('C4', 'C4'), 'P')
  t.equal(intervalQuality('C4', 'Db4'), 'm')
  t.equal(intervalQuality('C4', 'D4'), 'M')
  t.equal(intervalQuality('C4', 'Eb4'), 'm')
  t.equal(intervalQuality('C4', 'E4'), 'M')
  t.equal(intervalQuality('C4', 'F4'), 'P')
  t.equal(intervalQuality('C4', 'F#4'), 'A')
  t.equal(intervalQuality('C4', 'Gb4'), 'd')
  t.equal(intervalQuality('C4', 'G4'), 'P')
  t.equal(intervalQuality('C4', 'G#4'), 'A')
  t.equal(intervalQuality('C4', 'Ab4'), 'm')
  t.equal(intervalQuality('C4', 'A4'), 'M')
  t.equal(intervalQuality('C4', 'A#4'), 'A')
  t.equal(intervalQuality('C4', 'Bb4'), 'm')
  t.equal(intervalQuality('C4', 'B4'), 'M')
  t.equal(intervalQuality('C4', 'B#4'), 'A')
  t.equal(intervalQuality('C4', 'C5'), 'P')
  t.equal(intervalQuality('C4', 'Cb5'), 'd')
  t.equal(intervalQuality('C4', 'C#5'), 'A')
  t.equal(intervalQuality('B#3', 'C4'), 'd')
  t.equal(intervalQuality('Bb3', 'Bbb3'), 'A')
  t.equal(intervalQuality('B3', 'Ab4'), 'd')

  t.end()
})
